Adding more flags
OpenShopChannel/RepositoryManager pull request #3
Opened 2023-12-08 07:45 UTC by GabubuAvailable

Adding more flags for the apps which are compatible JUST with one system.

Flags:
- wii_only
- vwii_only
- wii_mini_only

2023-12-10 04:40 UTC, noahpistilli commented on hbb/routes.py
> +                long_description_prefix += "[CAUTION! Compatible just with the Wii mini!] "
Should the strings be have newlines?

2023-12-10 07:32 UTC, GabubuAvailable commented on hbb/routes.py
> +                long_description_prefix += "[CAUTION! Compatible just with the Wii mini!] "
Could you give me an example please?

2023-12-10 08:39 UTC, Artuto commented
I am concerned by the length of this prefix, as app descriptions will be cut off by the HBB after a certain length. Maybe it should be shorter?

2023-12-10 08:54 UTC, GabubuAvailable commented
> I am concerned by the length of this prefix, as app descriptions will be cut off by the HBB after a certain length. Maybe it should be shorter?

I've shorted the prefixes as much as I could. Could you re-check please?

2023-12-11 02:04 UTC, Artuto requested changes

2023-12-11 02:04 UTC, Artuto commented on hbb/routes.py
> +                long_description_prefix += "[Wii only app!] "
```suggestion
                long_description_prefix += "[Wii only] "
```

2023-12-11 02:04 UTC, Artuto commented on hbb/routes.py
> +                long_description_prefix += "[vWii only app!] "
```suggestion
                long_description_prefix += "[vWii only] "
```

2023-12-11 02:04 UTC, Artuto commented on hbb/routes.py
> +                long_description_prefix += "[Wii mini only app!] "
```suggestion
                long_description_prefix += "[Wii mini only] "
```

2023-12-12 06:25 UTC, GabubuAvailable reviewed
Sorry for this delay. I did commit your requests. Could you double-check it?

2023-12-12 07:00 UTC, Artuto approved these changes

2023-12-12 07:00 UTC, merged